/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.colorbuttonpersonalizado;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author a21gonzalocm
 */
public class PanelSelectColorPersonalizado extends javax.swing.JPanel {

    private Color selectedTextColor = new Color(100, 100, 100);
    private Color selectedBackgroundColor = new Color(100, 100, 100);

    /**
     * Creates new form PanelSelectColorPersonalizado
     */
    public PanelSelectColorPersonalizado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCorTexto = new javax.swing.JLabel();
        jlCorFondo = new javax.swing.JLabel();
        jtfCorTexto = new javax.swing.JTextField();
        jtfCorFondo = new javax.swing.JTextField();
        btnCorTexto = new javax.swing.JButton();
        btnCorFondo = new javax.swing.JButton();

        jlCorTexto.setText("Cor texto:");

        jlCorFondo.setText("Cor fondo:");

        jtfCorTexto.setEditable(false);
        jtfCorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCorTextoActionPerformed(evt);
            }
        });

        jtfCorFondo.setEditable(false);

        btnCorTexto.setText("...");
        btnCorTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorTextoActionPerformed(evt);
            }
        });

        btnCorFondo.setText("...");
        btnCorFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorFondoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCorTexto)
                        .addGap(18, 18, 18)
                        .addComponent(jtfCorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCorFondo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfCorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCorTexto)
                    .addComponent(btnCorFondo))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCorTexto)
                    .addComponent(jtfCorTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCorFondo)
                    .addComponent(jtfCorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorFondo))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCorTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCorTextoActionPerformed

    private void btnCorTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorTextoActionPerformed
        selectedTextColor = JColorChooser.showDialog(btnCorFondo, "Seleciona a cor do texto", Color.BLACK);
        int red = selectedTextColor.getRed();
        int blue = selectedTextColor.getBlue();
        int green = selectedTextColor.getGreen();
        jtfCorTexto.setText("["+red + "," + green + "," + blue+"]");
    }//GEN-LAST:event_btnCorTextoActionPerformed

    private void btnCorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorFondoActionPerformed
        selectedBackgroundColor = JColorChooser.showDialog(btnCorFondo, "Seleciona a cor de fondo", Color.BLACK);

        int red = selectedBackgroundColor.getRed();
        int blue = selectedBackgroundColor.getBlue();
        int green = selectedBackgroundColor.getGreen();
        jtfCorFondo.setText("["+red + "," + green + "," + blue+"]");

    }//GEN-LAST:event_btnCorFondoActionPerformed

    public Cor getSelectedValue() {

        Cor cor = new Cor(selectedTextColor, selectedBackgroundColor);

        return cor;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCorFondo;
    private javax.swing.JButton btnCorTexto;
    private javax.swing.JLabel jlCorFondo;
    private javax.swing.JLabel jlCorTexto;
    private javax.swing.JTextField jtfCorFondo;
    private javax.swing.JTextField jtfCorTexto;
    // End of variables declaration//GEN-END:variables
}
